#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Tue Jan 17 10:40:26 2023
#

import wx,os
import glob

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        self.text_ctrl_1 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_2.Add(self.text_ctrl_1, 0, wx.EXPAND, 0)

        self.tree_ctrl_1 = wx.TreeCtrl(self.panel_1, wx.ID_ANY)
        sizer_2.Add(self.tree_ctrl_1, 1, wx.EXPAND, 0)

        self.list_ctrl_1 = wx.ListCtrl(self.panel_1, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        self.list_ctrl_1.AppendColumn("A", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.list_ctrl_1.AppendColumn("B", format=wx.LIST_FORMAT_LEFT, width=-1)
        sizer_1.Add(self.list_ctrl_1, 1, wx.EXPAND, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.Bind(wx.EVT_TEXT, self.enter_text, self.text_ctrl_1)
        self.Bind(wx.EVT_TREE_SEL_CHANGED, self.select_item, self.tree_ctrl_1)
        # end wxGlade

    def enter_text(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'enter_text' not implemented!")
        path=self.text_ctrl_1.GetValue()
        dir = os.listdir(path)

        matsubi = path.rfind('\\')
        target = path[matsubi+1:]

        imageList = wx.ImageList(16,16)
        idx2 = imageList.Add(wx.ArtProvider.GetBitmap(wx.ART_NEW,wx.ART_OTHER,(16,16)))

        root = self.tree_ctrl_1.AddRoot(target,0,0,)
        for d in dir:
            self.tree_ctrl_1.AppendItem(root, str(d), idx2, -1, None)
        event.Skip()

    def select_item(self, event):  # wxGlade: MyFrame.<event_handler>
        self.list_ctrl_1.DeleteAllItems()
        try:
            path=self.text_ctrl_1.GetValue()
            folder=self.tree_ctrl_1.GetItemText(self.tree_ctrl_1.GetSelection())
            target_path=os.path.join(path, folder).replace("\\","/")

            # ファイル一覧
            count = 0
            files = glob.glob(target_path+"/*.csv")
            for file in files:
                tmp = file.rfind('\\')
                tmp = file[tmp+1:]
                self.list_ctrl_1.InsertItem(count,tmp)
                tmp=sum(1 for line in open(os.path.join(target_path,file), "rb"))
                self.list_ctrl_1.SetItem(count,1,str(tmp))
                count = count + 1
        except Exception as e:
            print(e)
            pass
        event.Skip()

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
